### PR TITLE
Add intellisense types, fix reactivity issues, allow kebab-case properties

### PR DESCRIPTION
**Pull request by kswzr**

### CODE REVIEW

**Comment by kswzr** [comment]
Hey @sfxcode, I've although thought about using v-bind="$attrs", but then component properties could not be used in kebab-case style.

**Comment by sfxcode** [comment]
Hi Kevin, nice work and good point with the kebab case properties. I will look into this in the evening. Disadvantage is v-bind allows additional properties that are not part of the implementation and deleting it will prevent using them ...
But in general you are right,

Greetings,

Tom

**Comment by sfxcode** [comment]
Sadly i think you are behind the latest changes where i switched to unbuild, so merging will be a problem, because the structure has changed, maybe you can check it

**Comment by kswzr** [comment]
Sure, I will check that. 

> i do not understand the formkit folder in the src dir of your branch

You're right. That's a fault. Something gone wrong during comparison with my project, will fix that later.

> Hi Kevin, nice work and good point with the kebab case properties. I will look into this in the evening. Disadvantage is v-bind allows additional properties that are not part of the implementation and deleting it will prevent using them ... But in general you are right,
> 
> Greetings,
> 
> Tom

I would suggest that we add the `v-bind="$attrs"` as first argument, to no loose what you have described.
Also we can override then the attrs parameters with the context ones :)

**Comment by sfxcode** [comment]
> I would suggest that we add the `v-bind="$attrs"` as first argument, to no loose what you have described.
> Also we can override then the attrs parameters with the context ones :)

Perfect, make it so ...

Greetings from Würzburg

**Comment by sfxcode** [comment]
Again, very cool that you take part in this project ...

**Comment by kswzr** [comment]
@sfxcode could review my changes, please? I've fixed all the issues caused by rebase and added the v-bind property. 

I am currently seeing one task regarding the `icon` property. I have seen in your changelog that there are things changed by PrimeVue. Maybe you could explain that, so I can adapt it to that?

**Comment by sfxcode** [comment]
> @sfxcode could review my changes, please? I've fixed all the issues caused by rebase and added the v-bind property.
> 
> I am currently seeing one task regarding the `icon` property. I have seen in your changelog that there are things changed by PrimeVue. Maybe you could explain that, so I can adapt it to that?

Done, some minor fixes, Icons on Text Field replaced by PrimeVue IconField
Tried to use value instead of v-bind like it is written by formkit, but many things does not wotk and some side effects, so i reverted it.

Again, ty for your very nice work.

Given something back was also my reason do make some public repositories.

Have a great coding time,

Tom

**Comment by kswzr** [comment]
> Hi, one question,
> 
> have you committed with an email that is not connected to your github account?
> 
> You have made very good additions but you are not showed up in the list of comitters ....
> 
> Anyway, thanks again for supporting open source projects !
> 
> Greetings,
> 
> Tom

Yes, you're right. May I rebase those commits and change the author email?

**Pull request merged**
